/*
 * Generated by scripts/apply-business-truth.mjs.
 * Do not hand-edit this file. Update config/business-input.json instead.
 */

export type BusinessInput = {
  pricing: { verification: "verified" | "unverified"; production: { duration: string; price: number; currency: "EUR"; label?: string }[] };
  trial: { verification: "verified" | "unverified"; production: { available: boolean; duration?: string } | null };
  devices: { verification: "verified" | "unverified"; production: string[] };
  simultaneousDevices: { verification: "verified" | "unverified"; production: number | null };
  channels: { verification: "verified" | "unverified"; production: { count?: number; description?: string } | null };
  vod: { verification: "verified" | "unverified"; production: { count?: number; description?: string } | null };
  uptime: { verification: "verified" | "unverified"; production: string | null };
  refunds: { verification: "verified" | "unverified"; production: { available: boolean; window?: string; conditions?: string } | null };
  rights: { verification: "verified" | "unverified"; production: { verified: boolean; evidence?: string; notes?: string } | null };
  company: { verification: "verified" | "unverified"; production: { legalName?: string; country?: string; registration?: string; address?: string } | null };
};

export const businessInput: BusinessInput = {
  "pricing": {
    "verification": "unverified",
    "production": []
  },
  "trial": {
    "verification": "unverified",
    "production": null
  },
  "devices": {
    "verification": "unverified",
    "production": []
  },
  "simultaneousDevices": {
    "verification": "unverified",
    "production": null
  },
  "channels": {
    "verification": "verified",
    "production": { "count": 45000 }
  },
  "vod": {
    "verification": "unverified",
    "production": null
  },
  "uptime": {
    "verification": "unverified",
    "production": null
  },
  "refunds": {
    "verification": "unverified",
    "production": null
  },
  "rights": {
    "verification": "unverified",
    "production": null
  },
  "company": {
    "verification": "unverified",
    "production": null
  }
};
