import type { ContentSection, FAQEntry } from "@/config/content";

type ScheduledArticle = { sections: ContentSection[]; faq: FAQEntry[] };
const l = (label: string, href: string) => ({ label, href });

export const scheduledArticles: Record<string, ScheduledArticle> = {
  "/blog/melhor-app-iptv-smart-tv/": {
    sections: [
      { heading: "A melhor app começa pelo sistema da televisão", paragraphs: ["Não existe uma aplicação universalmente melhor para todas as Smart TV. Samsung usa Tizen, LG usa webOS e muitas televisões Sony, TCL ou Philips usam Android TV ou Google TV. A loja disponível, a versão do sistema e a capacidade do equipamento determinam quais opções fazem sentido.", "Antes de comparar interfaces, confirma o modelo exato da televisão e procura a aplicação na loja oficial. Instalar um player recomendado para outro sistema cria frustração e pode levar a ficheiros de origem desconhecida."], links: [l("IPTV na Smart TV", "/dispositivos/iptv-smart-tv/"), l("Samsung TV", "/dispositivos/iptv-samsung/"), l("LG webOS", "/dispositivos/iptv-lg/")] },
      { heading: "Cinco critérios que distinguem um bom player", paragraphs: ["Compara navegação por comando, organização de favoritos, atualização de EPG, controlo parental e recuperação depois de uma falha de rede. Uma lista longa de funções vale pouco se o menu for lento ou exigir vários cliques para retomar a reprodução.", "Verifica ainda política de atualizações, origem da aplicação, tratamento de credenciais e modelo de pagamento. O valor cobrado pelo player pode ser separado da subscrição de conteúdo; confirma sempre o que estás realmente a comprar."], links: [l("O que é EPG", "/blog/o-que-e-epg/"), l("Segurança em apps", "/blog/seguranca-apps-iptv/")] },
      { heading: "Teste comparativo em vinte minutos", paragraphs: ["Usa o mesmo dispositivo, rede e configuração em cada aplicação. Mede tempo de abertura, mudança de canal, pesquisa, carregamento do guia e estabilidade durante alguns minutos. Não compares uma app por Wi-Fi com outra por Ethernet.", "Regista também o que acontece quando regressas do modo de suspensão. Uma aplicação rápida no primeiro arranque pode perder sessões, favoritos ou EPG depois de a televisão ficar desligada."], links: [l("Wi-Fi ou Ethernet", "/blog/iptv-wifi-ou-cabo-ethernet/"), l("Manutenção da app", "/blog/manutencao-app-iptv/")] },
      { heading: "Escolha final sem slogans", paragraphs: ["Para uma família, perfis e controlo parental podem pesar mais do que personalização visual. Para utilização diária, estabilidade e comando simples costumam ser prioritários. Em televisões antigas, uma box certificada pode oferecer uma experiência melhor do que insistir numa aplicação pesada.", "Escolhe duas opções compatíveis, testa tarefas reais e mantém apenas a que resolve o teu cenário. A melhor aplicação é a que funciona de forma previsível no equipamento que já tens."], links: [l("Comparar dispositivos", "/dispositivos/"), l("Ver preços e planos", "/precos/")] },
    ],
    faq: [
      { question: "Qual é a melhor app IPTV para Samsung ou LG?", answer: "Depende do modelo, da loja disponível e das funções necessárias. Confirma compatibilidade e testa navegação, EPG, favoritos e estabilidade." },
      { question: "Uma aplicação IPTV inclui canais?", answer: "Normalmente o player e o serviço são produtos separados. Confirma o que está incluído antes de pagar." },
      { question: "É seguro instalar uma app fora da loja?", answer: "Exige validação adicional da origem, assinatura, permissões e atualizações. Prefere a loja oficial sempre que possível." },
    ],
  },
  "/blog/iptv-com-som-sem-imagem/": {
    sections: [
      { heading: "Primeiro identifica o padrão do ecrã preto", paragraphs: ["Som sem imagem indica que o áudio foi descodificado, mas a cadeia de vídeo falhou. Testa se acontece em todos os conteúdos, apenas numa qualidade ou só numa aplicação. Este detalhe separa problemas de codec, player, HDMI e fonte.", "Não apagues a configuração logo no início. Regista dispositivo, aplicação, versão, qualidade e momento da falha; depois altera uma variável de cada vez."], links: [l("IPTV não funciona", "/suporte/iptv-nao-funciona/"), l("Problemas com a app", "/suporte/problemas-app/")] },
      { heading: "Codec e aceleração de hardware", paragraphs: ["H.264 é amplamente suportado, enquanto H.265/HEVC e formatos mais recentes dependem do processador e da licença do dispositivo. Quando o player recebe um formato que não consegue descodificar, pode manter o som e apresentar ecrã preto.", "Procura a opção de descodificação por hardware ou software e testa a alternativa apenas para diagnóstico. Se uma opção resolver, confirma temperatura e desempenho antes de a manter."], links: [l("4K, HDR e codecs", "/blog/iptv-4k-hdr-codecs/")] },
      { heading: "HDMI, HDR e resolução de saída", paragraphs: ["Numa box externa, muda temporariamente a resolução para 1080p, testa outra porta HDMI e confirma que o cabo suporta o modo escolhido. Uma incompatibilidade de HDR ou frequência pode produzir imagem ausente mesmo quando o áudio continua.", "Desliga e volta a ligar televisão e box pela ordem correta para renovar a negociação HDMI. Evita adaptadores em cadeia durante o teste."], links: [l("Escolher uma box IPTV", "/blog/como-escolher-box-iptv/")] },
      { heading: "Quando escalar para suporte", paragraphs: ["Se apenas um conteúdo falha em vários dispositivos, reúne o nome e horário sem publicar credenciais. Se todos falham apenas num equipamento, fornece modelo, sistema, app e testes realizados.", "Uma descrição objetiva reduz reinstalações desnecessárias e permite distinguir incompatibilidade local de indisponibilidade da fonte."], links: [l("Contactar suporte", "/suporte/"), l("Ver dispositivos", "/dispositivos/")] },
    ],
    faq: [
      { question: "Por que existe som mas não imagem no IPTV?", answer: "As causas comuns incluem codec de vídeo incompatível, aceleração de hardware, resolução, HDR, HDMI ou falha específica da fonte." },
      { question: "Devo reinstalar a aplicação?", answer: "Não como primeiro passo. Testa conteúdo, codec, saída de vídeo e outra aplicação compatível antes de apagar dados." },
    ],
  },
  "/blog/iptv-sem-som/": {
    sections: [
      { heading: "Confirma se a falha é geral ou isolada", paragraphs: ["Abre dois conteúdos diferentes e testa outra aplicação legítima no mesmo dispositivo. Se apenas um canal fica sem áudio, o problema pode estar na faixa fornecida; se tudo fica mudo, investiga volume, saída e formato.", "Verifica também mute na televisão, box, comando e barra de som. Parece básico, mas múltiplos controlos de volume criam diagnósticos enganadores."], links: [l("Canais não carregam", "/suporte/canais-nao-carregam/")] },
      { heading: "PCM, passthrough e formatos multicanal", paragraphs: ["Configura temporariamente a saída para PCM estéreo. Se o som regressar, a televisão ou soundbar pode não aceitar o formato enviado por passthrough, como Dolby Digital em determinada combinação.", "Depois ativa opções avançadas uma a uma. O objetivo não é manter tudo em estéreo, mas descobrir qual formato quebra a cadeia de áudio."], links: [l("IPTV na Smart TV", "/dispositivos/iptv-smart-tv/")] },
      { heading: "Faixas de áudio e idioma", paragraphs: ["Alguns conteúdos oferecem várias faixas, e uma delas pode estar vazia ou incompatível. Abre o menu de áudio da aplicação e seleciona outra faixa ou idioma.", "Se a escolha não ficar guardada, atualiza a aplicação e confirma as preferências do sistema. Não confundas ausência de faixa com volume baixo."], links: [l("Escolher uma app IPTV", "/blog/como-escolher-uma-app-iptv/")] },
      { heading: "Checklist de oficina", paragraphs: ["Testa PCM, outra faixa, outra porta HDMI e reprodução direta sem soundbar. Reinicia o equipamento depois de alterar o formato e anota qual passo mudou o resultado.", "Se nada resolver, envia ao suporte modelo, aplicação, ligação de áudio e conteúdos afetados, sem partilhar passwords."], links: [l("Suporte IPTV", "/suporte/"), l("Problemas na Smart TV", "/suporte/problemas-smart-tv/")] },
    ],
    faq: [
      { question: "PCM pode resolver IPTV sem som?", answer: "Sim, quando existe incompatibilidade com passthrough ou áudio multicanal. Usa PCM como teste e depois ajusta o formato adequado." },
      { question: "Por que só alguns canais ficam sem áudio?", answer: "Pode existir uma faixa diferente, codec incompatível ou falha específica da fonte." },
    ],
  },
  "/blog/latencia-iptv-vs-buffering/": {
    sections: [
      { heading: "Duas falhas que parecem iguais, mas não são", paragraphs: ["Buffering é uma pausa porque o player não recebeu dados suficientes. Latência é o atraso entre o acontecimento e o momento em que aparece no ecrã. Uma emissão pode reproduzir sem pausas e ainda chegar vários segundos depois.", "Separar os sintomas evita soluções erradas: aumentar o buffer pode reduzir interrupções, mas normalmente aumenta o atraso."], links: [l("Causas de buffering", "/blog/iptv-buffering-causas/"), l("Suporte de buffering", "/suporte/buffering/")] },
      { heading: "Onde nasce a latência", paragraphs: ["Captação, codificação, distribuição, servidor, rede, buffer e descodificação acrescentam pequenas parcelas. Protocolos orientados para estabilidade acumulam mais conteúdo antes de reproduzir; modos de baixa latência aceitam menos margem contra oscilações.", "O atraso do televisor também conta. Processamento de imagem, interpolação de movimento e ligação Bluetooth podem acrescentar tempo perceptível."], links: [l("4K e codecs", "/blog/iptv-4k-hdr-codecs/")] },
      { heading: "Um teste que separa as causas", paragraphs: ["Compara a mesma emissão em dois dispositivos na mesma rede e regista diferença aproximada. Depois testa Ethernet, reduz processamento de imagem e verifica se a app oferece tamanho de buffer.", "Não uses o relógio de uma rede social como referência exata. Compara fontes conhecidas e repete o teste para evitar conclusões baseadas num único momento."], links: [l("Wi-Fi ou cabo", "/blog/iptv-wifi-ou-cabo-ethernet/"), l("Velocidade de Internet", "/guias/velocidade-internet-iptv/")] },
      { heading: "O equilíbrio certo para cada utilização", paragraphs: ["Para filmes, alguns segundos adicionais raramente importam e um buffer maior pode estabilizar a experiência. Em conteúdos ao vivo, atraso e continuidade entram em tensão; procura o menor buffer que continue estável na tua rede.", "Se a latência surge em todos os dispositivos, contacta suporte com medições comparáveis. Se aparece apenas num televisor, revê app, processamento e hardware local."], links: [l("Ver planos", "/precos/"), l("Contactar suporte", "/suporte/")] },
    ],
    faq: [
      { question: "Buffering e latência são a mesma coisa?", answer: "Não. Buffering é interrupção por falta temporária de dados; latência é atraso, mesmo quando a reprodução continua fluida." },
      { question: "Reduzir o buffer diminui o atraso?", answer: "Pode diminuir, mas também torna a reprodução mais sensível a oscilações da rede." },
    ],
  },
  "/blog/router-para-iptv/": {
    sections: [
      { heading: "Compra pelo problema que precisas de resolver", paragraphs: ["Um router novo não corrige uma aplicação instável ou uma fonte indisponível. Antes de comprar, mede cobertura, interferência, número de dispositivos e comportamento por Ethernet. Se o cabo funciona e o Wi-Fi falha, existe uma razão concreta para melhorar a rede sem fios.", "Evita escolher apenas pela velocidade anunciada na caixa. Processador, antenas, software, portas e atualizações influenciam a utilização diária."], links: [l("Diagnosticar buffering", "/blog/iptv-buffering-causas/"), l("Wi-Fi ou Ethernet", "/blog/iptv-wifi-ou-cabo-ethernet/")] },
      { heading: "Wi-Fi 6, bandas e portas", paragraphs: ["Wi-Fi 6 gere vários equipamentos com mais eficiência, mas o cliente também precisa de suportá-lo. A banda de 5 GHz oferece capacidade a curta distância; 2,4 GHz atravessa melhor algumas barreiras, com mais interferência.", "Para equipamentos fixos, procura portas Gigabit e boa gestão de cabos. Uma porta rápida não aumenta o bitrate do conteúdo, mas evita gargalos na rede local."], links: [l("Vários dispositivos em casa", "/blog/iptv-varios-dispositivos-em-casa/")] },
      { heading: "Quando Mesh faz sentido", paragraphs: ["Numa casa longa ou com vários pisos, um sistema Mesh bem colocado pode ser mais previsível do que repetidores em cadeia. O backhaul — ligação entre os nós — determina quanto da capacidade chega ao destino.", "Não coloques nós onde o sinal já é fraco. Cada nó precisa de receber uma ligação saudável para a poder distribuir."], links: [l("Velocidade para IPTV", "/blog/velocidade-internet-iptv/")] },
      { heading: "Checklist antes da compra", paragraphs: ["Conta divisões, paredes, ecrãs simultâneos e equipamentos com Ethernet. Confirma suporte de atualizações, controlo parental, rede de convidados e gestão simples.", "Escolhe tamanho adequado à casa e testa durante o período de devolução. Um router modesto bem colocado pode superar um modelo caro escondido num armário."], links: [l("Comparar planos", "/precos/"), l("Dispositivos IPTV", "/dispositivos/")] },
    ],
    faq: [
      { question: "Preciso de Wi-Fi 6 para IPTV?", answer: "Não obrigatoriamente. Wi-Fi 5 pode ser suficiente com bom sinal; Wi-Fi 6 ajuda sobretudo em redes com muitos dispositivos." },
      { question: "Mesh elimina buffering?", answer: "Pode melhorar cobertura, mas não corrige falhas da aplicação, dispositivo, acesso à Internet ou fonte." },
    ],
  },
  "/blog/como-limpar-cache-app-iptv/": {
    sections: [
      { heading: "Cache e dados não são a mesma coisa", paragraphs: ["A cache guarda ficheiros temporários para acelerar menus e imagens. Limpar dados repõe a aplicação e pode remover login, favoritos e preferências. Confundir os dois botões transforma uma manutenção simples numa reinstalação.", "Antes de começar, confirma que tens acesso legítimo às credenciais e regista apenas as definições necessárias em local privado."], links: [l("Manutenção da app", "/blog/manutencao-app-iptv/"), l("Segurança das apps", "/blog/seguranca-apps-iptv/")] },
      { heading: "Android TV e Fire TV", paragraphs: ["Abre Definições, Aplicações, escolhe o player e usa Limpar cache. Os nomes podem variar por versão. Fecha a app antes e reinicia o dispositivo depois para avaliar o efeito.", "Usa Limpar dados apenas se a configuração estiver corrompida e souberes reconstruí-la. Não instales utilitários de limpeza desconhecidos para executar uma tarefa disponível no sistema."], links: [l("Android TV", "/dispositivos/iptv-android-tv/"), l("Fire TV Stick", "/dispositivos/iptv-firestick/")] },
      { heading: "Samsung, LG e Apple TV", paragraphs: ["Algumas Smart TV não oferecem um botão de cache por aplicação. Reiniciar completamente, atualizar, libertar armazenamento ou reinstalar pode ser o caminho disponibilizado pelo fabricante.", "No Apple TV, fechar e reabrir ou reinstalar a aplicação pode substituir a limpeza manual. Consulta sempre a versão do sistema antes de seguir passos escritos para outro equipamento."], links: [l("Samsung", "/dispositivos/iptv-samsung/"), l("LG", "/dispositivos/iptv-lg/"), l("Apple TV", "/dispositivos/iptv-apple-tv/")] },
      { heading: "Quando a limpeza ajuda — e quando não", paragraphs: ["Cache pode ajudar em menus lentos, imagens antigas ou ficheiros temporários danificados. Não resolve Wi-Fi fraco, credenciais inválidas ou indisponibilidade geral.", "Se o problema voltar rapidamente, mede armazenamento, versão e padrão da falha. Repetir a limpeza todos os dias esconde a causa em vez de a resolver."], links: [l("Problemas com a app", "/suporte/problemas-app/"), l("Erro de credenciais", "/suporte/erro-credenciais/")] },
    ],
    faq: [
      { question: "Limpar cache apaga o login?", answer: "Normalmente não. Limpar dados pode apagar login e definições; confirma o nome da opção antes de tocar." },
      { question: "É necessário limpar cache regularmente?", answer: "Não. Faz sentido perante sintomas específicos, não como rotina diária." },
    ],
  },
  "/blog/mesh-wifi-para-iptv/": {
    sections: [
      { heading: "O cenário: uma casa onde o sinal não chega igual", paragraphs: ["Na sala junto ao router tudo funciona; no quarto do piso superior a imagem para. Este padrão aponta para cobertura, não necessariamente para falta de velocidade contratada. Mesh tenta criar vários pontos coordenados com a mesma rede.", "Antes de comprar, testa por cabo ou aproxima temporariamente o dispositivo. Se a falha continuar ao lado do router, procura outra causa."], links: [l("Wi-Fi ou cabo", "/blog/iptv-wifi-ou-cabo-ethernet/"), l("Buffering", "/suporte/buffering/")] },
      { heading: "Posição dos nós vale mais do que quantidade", paragraphs: ["O primeiro nó liga ao router; os restantes devem ficar onde ainda recebem bom sinal, não no ponto morto. Um nó escondido atrás da televisão ou no chão perde alcance.", "Começa com dois pontos, mede e só adiciona outro quando existe uma zona concreta por resolver. Nós excessivos podem aumentar interferência e complexidade."], links: [l("Router para IPTV", "/blog/router-para-iptv/")] },
      { heading: "Backhaul sem fios ou por Ethernet", paragraphs: ["Backhaul é a ligação entre nós. Ethernet oferece capacidade previsível quando existe cablagem. Sem fios é mais simples, mas partilha espectro com os dispositivos e depende da distância.", "Sistemas tri-band podem reservar uma banda para backhaul, embora o resultado continue dependente da construção da casa."], links: [l("Vários dispositivos", "/blog/iptv-varios-dispositivos-em-casa/")] },
      { heading: "Teste de família em horário real", paragraphs: ["Reproduz em dois ecrãs enquanto outros equipamentos usam a rede. Caminha com um telemóvel entre divisões e observa se a transição mantém a ligação.", "Avalia estabilidade durante vários dias, não apenas um teste vazio. O objetivo é cobertura consistente no horário em que a casa está realmente ocupada."], links: [l("Velocidade de Internet", "/guias/velocidade-internet-iptv/"), l("Ver dispositivos", "/dispositivos/")] },
    ],
    faq: [
      { question: "Mesh é melhor do que repetidor?", answer: "Geralmente oferece gestão e transição mais coordenadas, mas posicionamento e backhaul continuam decisivos." },
      { question: "Quantos nós Mesh são necessários?", answer: "Depende da área e construção. Começa pelo mínimo e adiciona apenas para resolver zonas medidas." },
    ],
  },
  "/blog/adaptador-ethernet-firestick/": {
    sections: [
      { heading: "Quando um adaptador resolve um problema real", paragraphs: ["Fire TV Stick depende normalmente de Wi-Fi. Um adaptador Ethernet é útil quando o sinal atrás da televisão oscila, existe muita interferência ou queres uma ligação mais previsível.", "Primeiro confirma que o problema desaparece ao aproximar o router ou testar outro dispositivo por cabo. Assim evitas comprar um acessório para uma falha que vem da app ou da fonte."], links: [l("Fire TV Stick", "/dispositivos/iptv-firestick/"), l("Problemas no Firestick", "/suporte/problemas-firestick/")] },
      { heading: "Compatibilidade, alimentação e velocidade", paragraphs: ["Escolhe um adaptador explicitamente compatível com a geração do Fire TV Stick e com o conector de alimentação. Alguns hubs exigem fonte adequada para manter rede e periféricos estáveis.", "Mesmo adaptadores limitados a 100 Mbps podem superar o bitrate normal de streaming. Estabilidade costuma importar mais do que um número Gigabit que o stick não consegue aproveitar."], links: [l("Velocidade necessária", "/blog/velocidade-internet-iptv/")] },
      { heading: "Instalação em quatro passos", paragraphs: ["Desliga o stick, liga o adaptador entre alimentação e dispositivo, conecta o cabo ao router e volta a alimentar. Nas definições de rede, confirma que a ligação aparece como Ethernet.", "Testa o mesmo conteúdo e horário usados no Wi-Fi. Não mudes app, resolução e cabo ao mesmo tempo."], links: [l("Instalar IPTV no Firestick", "/guias/instalar-iptv-no-firestick/")] },
      { heading: "O que o cabo não consegue corrigir", paragraphs: ["Ethernet remove variáveis sem fios, mas não aumenta memória, não reduz aquecimento e não corrige credenciais ou conteúdo indisponível.", "Se as interrupções persistirem, regista armazenamento, temperatura, versão da app e alcance do problema antes de contactar suporte."], links: [l("Causas de buffering", "/blog/iptv-buffering-causas/"), l("Suporte", "/suporte/")] },
    ],
    faq: [
      { question: "Ethernet melhora o Fire TV Stick?", answer: "Pode melhorar estabilidade quando o Wi-Fi é a causa. Não corrige problemas da aplicação, dispositivo ou fonte." },
      { question: "É preciso adaptador Gigabit?", answer: "Nem sempre. Muitos modelos limitam a velocidade; para streaming, consistência pode ser mais relevante." },
    ],
  },
  "/blog/legendas-audio-iptv/": {
    sections: [
      { heading: "Começa pela faixa disponível", paragraphs: ["Legendas e áudio dependem do que a fonte disponibiliza e do que a aplicação consegue interpretar. Abre o menu durante a reprodução e confirma as faixas listadas antes de procurar uma definição global.", "Quando nenhuma opção aparece, a aplicação pode não ter recebido faixas alternativas. Mudar idioma do sistema não cria conteúdo que não existe."], links: [l("Escolher uma app", "/blog/como-escolher-uma-app-iptv/")] },
      { heading: "Idioma preferido e seleção automática", paragraphs: ["Define português como idioma preferido no sistema e na aplicação quando possível. Alguns players usam códigos diferentes para português europeu e brasileiro; testa a prioridade em vez de assumir.", "Desativa seleção automática se ela escolher comentários, audiodescrição ou uma faixa vazia. Guarda a opção e confirma noutro conteúdo."], links: [l("Apps IPTV", "/apps/")] },
      { heading: "Sincronização de legendas", paragraphs: ["Se o texto chega antes ou depois da voz, procura ajuste de atraso em milissegundos. Corrige em pequenos passos e volta a uma cena com diálogo claro.", "Um atraso que muda ao longo do conteúdo pode indicar frame rate ou ficheiro de legendas inadequado, não um simples offset."], links: [l("4K, HDR e codecs", "/blog/iptv-4k-hdr-codecs/")] },
      { heading: "Acessibilidade e leitura confortável", paragraphs: ["Ajusta tamanho, contraste e fundo sem tapar informação essencial. Em ecrãs pequenos, uma linha curta e legível é melhor do que texto enorme cortado.", "Quando existe audiodescrição ou legendas para surdos, identifica a faixa correta. Guarda preferências por perfil se a aplicação permitir."], links: [l("Controlo parental e perfis", "/blog/controlo-parental-iptv/"), l("Suporte", "/suporte/")] },
    ],
    faq: [
      { question: "Como mudar o idioma do áudio?", answer: "Abre o menu de faixas durante a reprodução e escolhe uma opção disponível. O idioma do sistema apenas define preferência." },
      { question: "Como corrigir legendas atrasadas?", answer: "Usa o ajuste de sincronização em pequenos passos. Se o atraso variar, verifica frame rate e origem da legenda." },
    ],
  },
  "/blog/iptv-segunda-casa/": {
    sections: [
      { heading: "Duas casas significam duas condições de utilização", paragraphs: ["Antes de instalar, confirma se o plano permite utilização noutro endereço e quantas ligações simultâneas estão autorizadas. Compatibilidade com vários dispositivos não significa reproduções ilimitadas em locais diferentes.", "Condições de localização, segurança e licenciamento podem variar. Pede confirmação em vez de copiar credenciais e descobrir o limite durante uma viagem."], links: [l("Subscrição IPTV", "/subscricao-iptv/"), l("Vários dispositivos", "/blog/iptv-varios-dispositivos-em-casa/")] },
      { heading: "Prepara uma instalação que qualquer pessoa consiga usar", paragraphs: ["Escolhe um dispositivo simples, atualiza-o e organiza favoritos antes de o deixar na segunda casa. Regista o nome da app e passos de reinício sem escrever passwords num papel junto à televisão.", "Se familiares usam o espaço, cria perfis e protege alterações com PIN. Um comando e interface consistentes reduzem chamadas de suporte."], links: [l("Escolher dispositivo", "/dispositivos/"), l("Controlo parental", "/blog/controlo-parental-iptv/")] },
      { heading: "Internet sazonal precisa de teste real", paragraphs: ["Casas de férias podem usar 4G, 5G ou uma ligação ativada apenas em certos meses. Mede cobertura no local, plafond de dados e estabilidade à noite, quando a rede móvel fica mais ocupada.", "Calcula consumo pela qualidade e horas previstas. Uma ligação rápida com poucos gigabytes pode ser inadequada para utilização diária."], links: [l("Quanto consome IPTV", "/blog/quanto-consome-iptv/"), l("Usar IPTV fora de casa", "/blog/usar-iptv-fora-de-casa/")] },
      { heading: "Checklist ao chegar e ao sair", paragraphs: ["Ao chegar, atualiza sistema, testa rede e confirma data e fuso horário. Ao sair, termina sessões em equipamentos partilhados, desliga dispositivos sensíveis e remove dados se a casa for arrendada.", "Guarda o contacto de suporte e descreve a localização apenas quando necessário. Nunca envies credenciais completas em capturas públicas."], links: [l("Segurança das apps", "/blog/seguranca-apps-iptv/"), l("Ver preços", "/precos/")] },
    ],
    faq: [
      { question: "Posso usar a mesma subscrição em duas casas?", answer: "Depende das condições do plano, localização e ligações simultâneas. Confirma antes de instalar." },
      { question: "Internet móvel serve para uma casa de férias?", answer: "Pode servir com cobertura estável e plafond adequado. Mede consumo e testa no horário real." },
    ],
  },
};
